/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class trigonal_tungsten_calculations_operations_equations_GaussSolverJNI */

#ifndef _Included_trigonal_tungsten_calculations_operations_equations_GaussSolverJNI
#define _Included_trigonal_tungsten_calculations_operations_equations_GaussSolverJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     trigonal_tungsten_calculations_operations_equations_GaussSolverJNI
 * Method:    solve
 * Signature: ([[D[DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_trigonal_tungsten_calculations_operations_equations_GaussSolverJNI_solve
  (JNIEnv *, jclass, jobjectArray, jdoubleArray, jint);

/*
 * Class:     trigonal_tungsten_calculations_operations_equations_GaussSolverJNI
 * Method:    getExecutionTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_trigonal_tungsten_calculations_operations_equations_GaussSolverJNI_getExecutionTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
