/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class trigonal_tungsten_calculations_operations_equations_NonlinearEquationSolverJNI */

#ifndef _Included_trigonal_tungsten_calculations_operations_equations_NonlinearEquationSolverJNI
#define _Included_trigonal_tungsten_calculations_operations_equations_NonlinearEquationSolverJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     trigonal_tungsten_calculations_operations_equations_NonlinearEquationSolverJNI
 * Method:    solve
 * Signature: ([DIDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_trigonal_tungsten_calculations_operations_equations_NonlinearEquationSolverJNI_solve
  (JNIEnv *, jclass, jdoubleArray, jint, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
